'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class employee

    '''<summary>
    '''_employee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _employee As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''tmrThread control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tmrThread As Global.DevExpress.Web.ASPxTimer.ASPxTimer

    '''<summary>
    '''cpPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpPage As Global.DevExpress.Web.ASPxCallback.ASPxCallback

    '''<summary>
    '''tabEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabEmployee As Global.DevExpress.Web.ASPxTabControl.ASPxPageControl

    '''<summary>
    '''lblEmployeeNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployeeNum As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtEmployeeNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmployeeNum As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblPreferredName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPreferredName As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtPreferredName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPreferredName As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTitle As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirstName As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFirstName As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblOtherName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOtherName As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtOtherNames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherNames As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblSurname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSurname As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtSurname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSurname As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblIDNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIDNum As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtIDNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDNum As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblSex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSex As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbSex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSex As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblNationality control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNationality As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbNationality control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbNationality As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBirthDate As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''dteBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteBirthDate As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''lblEthnicGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEthnicGroup As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbEthnicGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbEthnicGroup As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblMaritalStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaritalStatus As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbMaritalStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbMaritalStatus As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''tblAdress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblAdress As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lblAddressLong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddressLong As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblPostalAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPostalAddress As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblSARSAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSARSAddress1 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtSARSAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSARSAddress1 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblPostalAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPostalAddress1 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtPOBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOBox As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblSARSAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSARSAddress2 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtSARSAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSARSAddress2 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblPostalAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPostalAddress2 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtPOArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOArea As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblSARSAddress3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSARSAddress3 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtSARSAddress3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSARSAddress3 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblPostalAddress3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPostalAddress3 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtPOCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOCode As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblSARSAddress4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSARSAddress4 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtSARSAddress4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSARSAddress4 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblSARSAddress5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSARSAddress5 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtSARSAddress5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSARSAddress5 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblSARSAddress6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSARSAddress6 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtSARSAddress6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSARSAddress6 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblSARSAddress7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSARSAddress7 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtSARSAddress7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSARSAddress7 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblCellTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCellTel As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtCellTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCellTel As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblHomeTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHomeTel As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtHomeTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHomeTel As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmailAddress As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailAddress As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblEmailAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmailAddress1 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtEmailAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailAddress1 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblJobTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJobTitle As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbJobTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbJobTitle As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblJobGrade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJobGrade As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbJobGrade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbJobGrade As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblCostCentre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCostCentre As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbCostCentre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCostCentre As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblDeptName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeptName As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbDeptName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbDeptName As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblSkill_Level control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSkill_Level As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbSkill_Level control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSkill_Level As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblAppointype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppointype As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbAppointype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAppointype As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPosition As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPosition As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocation As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbLocation As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblDateJoinedGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateJoinedGroup As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''dteDateJoinedGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteDateJoinedGroup As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''lblAppointdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppointdate As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''dteAppointdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteAppointdate As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''dgExports_002 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgExports_002 As Global.DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter

    '''<summary>
    '''dgView_002 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgView_002 As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''delete_002 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents delete_002 As Global.DevExpress.Web.ASPxGridView.GridViewCommandColumnCustomButton

    '''<summary>
    '''pnlSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSubmit As Global.DevExpress.Web.ASPxPanel.ASPxPanel

    '''<summary>
    '''upDoc_001 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upDoc_001 As Global.DevExpress.Web.ASPxUploadControl.ASPxUploadControl

    '''<summary>
    '''upDoc_002 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upDoc_002 As Global.DevExpress.Web.ASPxUploadControl.ASPxUploadControl

    '''<summary>
    '''upDoc_003 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upDoc_003 As Global.DevExpress.Web.ASPxUploadControl.ASPxUploadControl

    '''<summary>
    '''upDoc_004 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upDoc_004 As Global.DevExpress.Web.ASPxUploadControl.ASPxUploadControl

    '''<summary>
    '''pnlApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlApprove As Global.DevExpress.Web.ASPxPanel.ASPxPanel

    '''<summary>
    '''dgView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgView As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''cmdApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdApprove As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''cmdReject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdReject As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''dsCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCategory As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsDisability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDisability As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsEthnicGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsEthnicGroup As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsMaritalStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsMaritalStatus As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsNationality control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsNationality As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsNoKRelationship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsNoKRelationship As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsRelationship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsRelationship As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsReligion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsReligion As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsTitle As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsSex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsSex As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsAppointype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAppointype As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsCostCentre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCostCentre As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsDeptName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDeptName As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsJobGrade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsJobGrade As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsJobTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsJobTitle As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsLocation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsPosition As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsReportToCompNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsReportToCompNum As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsReportToEmpNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsReportToEmpNum As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsReportsToType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsReportsToType As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsSkill_Level control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsSkill_Level As Global.System.Web.UI.WebControls.SqlDataSource
End Class
