'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class index

    '''<summary>
    '''_index control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _index As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''mnuProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuProfile As Global.DevExpress.Web.ASPxMenu.ASPxPopupMenu

    '''<summary>
    '''hPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hPanel As Global.DevExpress.Web.ASPxHiddenField.ASPxHiddenField

    '''<summary>
    '''lpPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lpPage As Global.DevExpress.Web.ASPxLoadingPanel.ASPxLoadingPanel

    '''<summary>
    '''geTimeout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents geTimeout As Global.DevExpress.Web.ASPxGlobalEvents.ASPxGlobalEvents

    '''<summary>
    '''cpPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpPage As Global.DevExpress.Web.ASPxCallback.ASPxCallback

    '''<summary>
    '''tmrCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tmrCount As Global.DevExpress.Web.ASPxTimer.ASPxTimer

    '''<summary>
    '''tmrTimeout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tmrTimeout As Global.DevExpress.Web.ASPxTimer.ASPxTimer

    '''<summary>
    '''pcDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcDelete As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

    '''<summary>
    '''chkConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkConfirm As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

    '''<summary>
    '''cmdYes_001 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdYes_001 As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''cmdNo_001 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdNo_001 As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''pcCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcCompany As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

    '''<summary>
    '''tlvCompanies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tlvCompanies As Global.DevExpress.Web.ASPxTreeList.ASPxTreeList

    '''<summary>
    '''dgSavedAppz control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgSavedAppz As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''pnlCompanySwitch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCompanySwitch As Global.DevExpress.Web.ASPxPanel.ASPxPanel

    '''<summary>
    '''cmdSwitch_Company control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSwitch_Company As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''pnlCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCompany As Global.DevExpress.Web.ASPxPanel.ASPxPanel

    '''<summary>
    '''cmdOK_Company control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdOK_Company As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''cmdCancel_Company control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCancel_Company As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''pcSubmit_014 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcSubmit_014 As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

    '''<summary>
    '''cmdYes_014 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdYes_014 As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''cmdNo_014 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdNo_014 As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''pcYesOrNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcYesOrNo As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

    '''<summary>
    '''cmdYes_007 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdYes_007 As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''cmdNo_007 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdNo_007 As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''pcPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcPopup As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

    '''<summary>
    '''lblMessage_Popup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage_Popup As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmdPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdPopup As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''pcProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcProgress As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

    '''<summary>
    '''pbProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pbProgress As Global.DevExpress.Web.ASPxEditors.ASPxProgressBar

    '''<summary>
    '''pcTimeout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcTimeout As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

    '''<summary>
    '''lblTimeout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTimeout As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmdYes_002 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdYes_002 As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''cmdNo_002 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdNo_002 As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''cpPanes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpPanes As Global.DevExpress.Web.ASPxCallbackPanel.ASPxCallbackPanel

    '''<summary>
    '''spIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spIndex As Global.DevExpress.Web.ASPxSplitter.ASPxSplitter

    '''<summary>
    '''cpImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpImage As Global.DevExpress.Web.ASPxCallbackPanel.ASPxCallbackPanel

    '''<summary>
    '''imgPicture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPicture As Global.DevExpress.Web.ASPxEditors.ASPxBinaryImage

    '''<summary>
    '''lblSummary_001 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSummary_001 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblSummary_002 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSummary_002 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblSummary_003 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSummary_003 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''imgCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCompany As Global.DevExpress.Web.ASPxEditors.ASPxBinaryImage

    '''<summary>
    '''tb_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_search As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''tb_contacts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_contacts As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''tb_employee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_employee As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''tb_delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_delete As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''tb_transfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_transfer As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''cmbEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbEmployee As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyName As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDivision As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblSubDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubDivision As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblSubSubDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubSubDivision As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''navMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents navMenu As Global.DevExpress.Web.ASPxNavBar.ASPxNavBar
End Class
