'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class loansman

    '''<summary>
    '''_loansman control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _loansman As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''cpPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpPage As Global.DevExpress.Web.ASPxCallback.ASPxCallback

    '''<summary>
    '''pnlLoans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLoans As Global.DevExpress.Web.ASPxRoundPanel.ASPxRoundPanel

    '''<summary>
    '''dgView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgView As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''lblRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRemarks As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemarks As Global.DevExpress.Web.ASPxEditors.ASPxMemo

    '''<summary>
    '''tblButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblButtons As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''cmdApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdApprove As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''cmdReject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdReject As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''dsDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDescription As Global.System.Web.UI.WebControls.SqlDataSource
End Class
