'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class organisational

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''_personal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _personal As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''cpPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpPage As Global.DevExpress.Web.ASPxCallback.ASPxCallback

    '''<summary>
    '''pcCostCentre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcCostCentre As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

    '''<summary>
    '''PopupControlContentControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlContentControl1 As Global.DevExpress.Web.ASPxPopupControl.PopupControlContentControl

    '''<summary>
    '''tblCostCentre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblCostCentre As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''dgView_001 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgView_001 As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''cmdOK_CostCentre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdOK_CostCentre As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''tabOrganizational control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabOrganizational As Global.DevExpress.Web.ASPxTabControl.ASPxPageControl

    '''<summary>
    '''ContentControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl1 As Global.DevExpress.Web.ASPxClasses.ContentControl

    '''<summary>
    '''lblDateJoinedGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateJoinedGroup As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''dteDateJoinedGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteDateJoinedGroup As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''lblAppointdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppointdate As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''dteAppointdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteAppointdate As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''lblYearsServiceG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYearsServiceG As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtYearsServiceG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYearsServiceG As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblYearsServiceA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYearsServiceA As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtYearsServiceA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYearsServiceA As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDivision As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbDivision As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblAppointype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppointype As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbAppointype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAppointype As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDepartment As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbDepartment As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblSkill_Level control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSkill_Level As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbSkill_Level control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSkill_Level As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSection As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSection As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblCostCentre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCostCentre As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbCostCentre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCostCentre As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''cmdCostCentre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCostCentre As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''lblJobTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJobTitle As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbJobTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbJobTitle As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblJobGrade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJobGrade As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbJobGrade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbJobGrade As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCategory As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblPayLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPayLevel As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbPayLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPayLevel As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblShifting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShifting As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbShifting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbShifting As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblFixed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFixed As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbFixed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbFixed As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblWorkAssignment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWorkAssignment As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbWorkAssignment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbWorkAssignment As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblUnionAffiliation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnionAffiliation As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbUnionAffiliation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbUnionAffiliation As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''ContentControl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl2 As Global.DevExpress.Web.ASPxClasses.ContentControl

    '''<summary>
    '''dgExports_002 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgExports_002 As Global.DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter

    '''<summary>
    '''dgView_002 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgView_002 As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''delete_002 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents delete_002 As Global.DevExpress.Web.ASPxGridView.GridViewCommandColumnCustomButton

    '''<summary>
    '''ContentControl3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl3 As Global.DevExpress.Web.ASPxClasses.ContentControl

    '''<summary>
    '''dgExports_003 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgExports_003 As Global.DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter

    '''<summary>
    '''dgView_003 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgView_003 As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''delete_003 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents delete_003 As Global.DevExpress.Web.ASPxGridView.GridViewCommandColumnCustomButton

    '''<summary>
    '''ContentControl6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl6 As Global.DevExpress.Web.ASPxClasses.ContentControl

    '''<summary>
    '''dgView_Movement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgView_Movement As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''ContentControl7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl7 As Global.DevExpress.Web.ASPxClasses.ContentControl

    '''<summary>
    '''ASPxLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel1 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''ASPxLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel2 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''ASPxLabel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel3 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblMALE_MGRSpecialPoloshirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMALE_MGRSpecialPoloshirt As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtMALE_MGRSpecialPoloshirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMALE_MGRSpecialPoloshirt As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblFEMALE_MGRSpecialPoloshirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFEMALE_MGRSpecialPoloshirt As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtFEMALE_MGRSpecialPoloshirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFEMALE_MGRSpecialPoloshirt As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblUNISEX_ProdSUShirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUNISEX_ProdSUShirt As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtUNISEX_ProdSUShirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUNISEX_ProdSUShirt As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblMALE_SUSpecialPoloshirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMALE_SUSpecialPoloshirt As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtMALE_SUSpecialPoloshirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMALE_SUSpecialPoloshirt As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblFEMALE_SUSpecialPoloshirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFEMALE_SUSpecialPoloshirt As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtFEMALE_SUSpecialPoloshirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFEMALE_SUSpecialPoloshirt As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblUNISEX_ProdRNFShirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUNISEX_ProdRNFShirt As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtUNISEX_ProdRNFShirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUNISEX_ProdRNFShirt As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblMALE_Polo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMALE_Polo As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtMALE_Polo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMALE_Polo As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblFEMALE_Blouse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFEMALE_Blouse As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtFEMALE_Blouse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFEMALE_Blouse As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblUNISEX_MaongPants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUNISEX_MaongPants As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtUNISEX_MaongPants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUNISEX_MaongPants As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblMALE_MaleShirtpackShort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMALE_MaleShirtpackShort As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtMALE_MaleShirtpackShort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMALE_MaleShirtpackShort As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblFEMALE_FemaleShirtpackShort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFEMALE_FemaleShirtpackShort As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtFEMALE_FemaleShirtpackShort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFEMALE_FemaleShirtpackShort As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblUNISEX_RepellantPants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUNISEX_RepellantPants As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtUNISEX_RepellantPants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUNISEX_RepellantPants As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblMALE_MaleShirtPackLong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMALE_MaleShirtPackLong As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtMALE_MaleShirtPackLong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMALE_MaleShirtPackLong As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblFEMALE_FemaleShirtPackLong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFEMALE_FemaleShirtPackLong As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtFEMALE_FemaleShirtPackLong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFEMALE_FemaleShirtPackLong As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblMALE_MaleBlackPants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMALE_MaleBlackPants As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtMALE_MaleBlackPants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMALE_MaleBlackPants As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblFEMALE_FemaleBlackPants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFEMALE_FemaleBlackPants As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtFEMALE_FemaleBlackPants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFEMALE_FemaleBlackPants As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblFEMALE_Skirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFEMALE_Skirt As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtFEMALE_Skirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFEMALE_Skirt As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblFEMALE_Blazer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFEMALE_Blazer As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtFEMALE_Blazer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFEMALE_Blazer As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''ASPxLabel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel4 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''ASPxLabel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel5 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblRESERVEDMALE_RNFSpecialShirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRESERVEDMALE_RNFSpecialShirt As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtRESERVEDMALE_RNFSpecialShirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRESERVEDMALE_RNFSpecialShirt As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblRESERVEDFEMALE_RNFSpecialShirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRESERVEDFEMALE_RNFSpecialShirt As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtRESERVEDFEMALE_RNFSpecialShirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRESERVEDFEMALE_RNFSpecialShirt As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblRESERVEDMALE_CampaignShirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRESERVEDMALE_CampaignShirt As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtRESERVEDMALE_CampaignShirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRESERVEDMALE_CampaignShirt As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblRESERVEDFEMALE_CampaignShirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRESERVEDFEMALE_CampaignShirt As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtRESERVEDFEMALE_CampaignShirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRESERVEDFEMALE_CampaignShirt As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblRESERVEDMALE_SpecialShirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRESERVEDMALE_SpecialShirt As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtRESERVEDMALE_SpecialShirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRESERVEDMALE_SpecialShirt As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblRESERVEDFEMALE_SpecialShirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRESERVEDFEMALE_SpecialShirt As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtRESERVEDFEMALE_SpecialShirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRESERVEDFEMALE_SpecialShirt As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblRESERVEDMALE_Polo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRESERVEDMALE_Polo2 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtRESERVEDMALE_Polo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRESERVEDMALE_Polo2 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblRESERVEDFEMALE_Blouse2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRESERVEDFEMALE_Blouse2 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtRESERVEDFEMALE_Blouse2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRESERVEDFEMALE_Blouse2 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblRESERVEDMALE_Polo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRESERVEDMALE_Polo3 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtRESERVEDMALE_Polo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRESERVEDMALE_Polo3 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblRESERVEDFEMALE_Blouse3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRESERVEDFEMALE_Blouse3 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtRESERVEDFEMALE_Blouse3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRESERVEDFEMALE_Blouse3 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblRESERVEDMALE_MaleSlacks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRESERVEDMALE_MaleSlacks As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtRESERVEDMALE_MaleSlacks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRESERVEDMALE_MaleSlacks As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblRESERVEDFEMALE_FemaleSlacks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRESERVEDFEMALE_FemaleSlacks As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtRESERVEDFEMALE_FemaleSlacks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRESERVEDFEMALE_FemaleSlacks As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblRESERVEDMALE_MaleSlacks2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRESERVEDMALE_MaleSlacks2 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtRESERVEDMALE_MaleSlacks2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRESERVEDMALE_MaleSlacks2 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblRESERVEDFEMALE_FemaleSlacks2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRESERVEDFEMALE_FemaleSlacks2 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtRESERVEDFEMALE_FemaleSlacks2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRESERVEDFEMALE_FemaleSlacks2 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblRESERVEDMALE_MaleBlackPants2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRESERVEDMALE_MaleBlackPants2 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtRESERVEDMALE_MaleBlackPants2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRESERVEDMALE_MaleBlackPants2 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblRESERVEDFEMALE_FemaleBlackPants2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRESERVEDFEMALE_FemaleBlackPants2 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtRESERVEDFEMALE_FemaleBlackPants2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRESERVEDFEMALE_FemaleBlackPants2 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblRESERVEDMALE_MaleSpecialJacket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRESERVEDMALE_MaleSpecialJacket As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtRESERVEDMALE_MaleSpecialJacket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRESERVEDMALE_MaleSpecialJacket As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblRESERVEDFEMALE_Skirt2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRESERVEDFEMALE_Skirt2 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtRESERVEDFEMALE_Skirt2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRESERVEDFEMALE_Skirt2 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblRESERVEDFEMALE_FemaleSpecialJacket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRESERVEDFEMALE_FemaleSpecialJacket As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtRESERVEDFEMALE_FemaleSpecialJacket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRESERVEDFEMALE_FemaleSpecialJacket As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''items_saved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents items_saved As Global.DevExpress.Web.ASPxHiddenField.ASPxHiddenField

    '''<summary>
    '''cmdSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmit As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''dsSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsSection As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDepartment As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDivision As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsAppointype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAppointype As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCategory As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsContractCostCentre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsContractCostCentre As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsContractDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsContractDept As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsContractJobGrade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsContractJobGrade As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsContractJobTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsContractJobTitle As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCompany As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsContracts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsContracts As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsContractStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsContractStatus As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsContractTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsContractTypes As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsCostCentre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCostCentre As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsDeptName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDeptName As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsFixed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsFixed As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsJobGrade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsJobGrade As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsJobTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsJobTitle As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsLocation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsPayLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsPayLevel As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsPosition As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsReportToCompNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsReportToCompNum As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsReportToEmpNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsReportToEmpNum As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsReportsToType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsReportsToType As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsShifting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsShifting As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsSkill_Level control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsSkill_Level As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsUnionAffiliation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsUnionAffiliation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsWorkAssignment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsWorkAssignment As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsShirtSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsShirtSize As Global.System.Web.UI.WebControls.SqlDataSource
End Class
