'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class transfer

    '''<summary>
    '''_transfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _transfer As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''cpPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpPage As Global.DevExpress.Web.ASPxCallback.ASPxCallback

    '''<summary>
    '''dteTransfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteTransfer As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''cmbReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbReason As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''dgView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgView As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''cmdSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmit As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''dsTransfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsTransfer As Global.System.Web.UI.WebControls.SqlDataSource
End Class
