--IF((SELECT COUNT(*) from [BloodTypeLU]) = 0)
--BEGIN
--    INSERT INTO [BloodTypeLU] VALUES ('A')
--    INSERT INTO [BloodTypeLU] VALUES ('B')
--    INSERT INTO [BloodTypeLU] VALUES ('AB')
--    INSERT INTO [BloodTypeLU] VALUES ('O')
--END
--GO
--2020-03-05
DELETE FROM BloodTypeLU
INSERT INTO BloodTypeLU VALUES('A')
INSERT INTO BloodTypeLU VALUES('B')
INSERT INTO BloodTypeLU VALUES('AB')
INSERT INTO BloodTypeLU VALUES('O')
INSERT INTO BloodTypeLU VALUES('A+')
INSERT INTO BloodTypeLU VALUES('A-')
INSERT INTO BloodTypeLU VALUES('B+')
INSERT INTO BloodTypeLU VALUES('B-')
INSERT INTO BloodTypeLU VALUES('O+')
INSERT INTO BloodTypeLU VALUES('O-')
INSERT INTO BloodTypeLU VALUES('AB+')
INSERT INTO BloodTypeLU VALUES('AB-')

GO

