 --2020-03-09
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Afghan')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Afghan')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Albanian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Albanian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Algerian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Algerian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('American')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('American')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Andorran')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Andorran')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Angolan')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Angolan')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Antiguans')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Antiguans')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Argentinean')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Argentinean')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Armenian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Armenian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Australian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Australian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Austrian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Austrian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Azerbaijani')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Azerbaijani')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Bahamian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Bahamian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Bahraini')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Bahraini')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Bangladeshi')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Bangladeshi')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Barbadian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Barbadian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Barbudans')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Barbudans')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Batswana')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Batswana')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Belarusian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Belarusian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Belgian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Belgian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Belizean')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Belizean')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Beninese')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Beninese')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Bhutanese')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Bhutanese')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Bolivian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Bolivian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Bosnian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Bosnian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Brazilian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Brazilian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('British')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('British')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Bruneian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Bruneian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Bulgarian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Bulgarian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Burkinabe')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Burkinabe')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Burmese')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Burmese')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Burundian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Burundian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Cambodian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Cambodian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Cameroonian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Cameroonian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Canadian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Canadian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Cape Verdean')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Cape Verdean')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Central African')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Central African')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Chadian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Chadian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Chilean')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Chilean')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Chinese')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Chinese')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Colombian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Colombian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Comoran')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Comoran')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Congolese')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Congolese')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Costa Rican')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Costa Rican')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Croatian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Croatian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Cuban')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Cuban')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Cypriot')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Cypriot')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Czech')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Czech')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Danish')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Danish')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Djibouti')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Djibouti')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Dominican')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Dominican')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Dutch')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Dutch')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('East Timorese')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('East Timorese')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Ecuadorean')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Ecuadorean')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Egyptian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Egyptian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Emirian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Emirian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Equatorial Guinean')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Equatorial Guinean')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Eritrean')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Eritrean')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Estonian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Estonian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Ethiopian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Ethiopian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Fijian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Fijian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Filipino')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Filipino')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Finnish')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Finnish')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('French')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('French')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Gabonese')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Gabonese')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Gambian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Gambian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Georgian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Georgian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('German')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('German')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Ghanaian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Ghanaian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Greek')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Greek')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Grenadian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Grenadian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Guatemalan')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Guatemalan')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Guinea-Bissauan')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Guinea-Bissauan')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Guinean')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Guinean')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Guyanese')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Guyanese')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Haitian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Haitian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Herzegovinian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Herzegovinian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Honduran')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Honduran')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Hungarian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Hungarian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('I-Kiribati')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('I-Kiribati')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Icelander')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Icelander')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Indian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Indian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Indonesian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Indonesian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Iranian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Iranian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Iraqi')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Iraqi')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Irish')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Irish')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Israeli')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Israeli')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Italian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Italian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Ivorian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Ivorian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Jamaican')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Jamaican')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Japanese')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Japanese')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Jordanian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Jordanian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Kazakhstani')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Kazakhstani')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Kenyan')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Kenyan')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Kittian and Nevisian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Kittian and Nevisian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Kuwaiti')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Kuwaiti')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Kyrgyz')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Kyrgyz')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Laotian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Laotian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Latvian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Latvian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Lebanese')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Lebanese')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Liberian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Liberian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Libyan')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Libyan')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Liechtensteiner')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Liechtensteiner')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Lithuanian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Lithuanian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Luxembourger')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Luxembourger')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Macedonian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Macedonian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Malagasy')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Malagasy')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Malawian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Malawian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Malaysian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Malaysian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Maldivian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Maldivian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Malian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Malian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Maltese')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Maltese')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Marshallese')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Marshallese')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Mauritanian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Mauritanian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Mauritian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Mauritian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Mexican')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Mexican')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Micronesian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Micronesian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Moldovan')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Moldovan')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Monacan')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Monacan')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Mongolian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Mongolian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Moroccan')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Moroccan')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Mosotho')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Mosotho')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Motswana')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Motswana')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Mozambican')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Mozambican')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Namibian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Namibian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Nauruan')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Nauruan')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Nepalese')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Nepalese')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('New Zealander')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('New Zealander')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Ni-Vanuatu')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Ni-Vanuatu')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Nicaraguan')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Nicaraguan')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Nigerian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Nigerian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Nigerien')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Nigerien')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('North Korean')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('North Korean')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Northern Irish')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Northern Irish')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Norwegian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Norwegian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Omani')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Omani')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Pakistani')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Pakistani')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Palauan')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Palauan')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Panamanian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Panamanian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Papua New Guinean')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Papua New Guinean')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Paraguayan')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Paraguayan')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Peruvian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Peruvian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Polish')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Polish')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Portuguese')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Portuguese')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Qatari')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Qatari')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Romanian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Romanian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Russian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Russian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Rwandan')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Rwandan')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Saint Lucian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Saint Lucian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Salvadoran')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Salvadoran')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Samoan')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Samoan')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('San Marinese')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('San Marinese')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Sao Tomean')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Sao Tomean')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Saudi')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Saudi')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Scottish')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Scottish')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Senegalese')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Senegalese')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Serbian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Serbian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Seychellois')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Seychellois')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Sierra Leonean')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Sierra Leonean')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Singaporean')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Singaporean')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Slovakian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Slovakian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Slovenian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Slovenian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Solomon Islander')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Solomon Islander')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Somali')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Somali')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('South African')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('South African')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('South Korean')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('South Korean')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Spanish')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Spanish')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Sri Lankan')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Sri Lankan')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Sudanese')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Sudanese')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Surinamer')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Surinamer')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Swazi')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Swazi')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Swedish')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Swedish')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Swiss')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Swiss')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Syrian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Syrian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Taiwanese')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Taiwanese')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Tajik')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Tajik')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Tanzanian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Tanzanian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Thai')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Thai')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Togolese')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Togolese')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Tongan')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Tongan')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Trinidadian or Tobagonian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Trinidadian or Tobagonian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Tunisian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Tunisian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Turkish')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Turkish')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Tuvaluan')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Tuvaluan')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Ugandan')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Ugandan')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Ukrainian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Ukrainian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Uruguayan')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Uruguayan')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Uzbekistani')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Uzbekistani')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Venezuelan')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Venezuelan')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Vietnamese')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Vietnamese')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Welsh')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Welsh')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Yemenite')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Yemenite')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Zambian')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Zambian')); END
 IF(NOT EXISTS(SELECT Nationality FROM NationalityLU WHERE Nationality = UPPER('Zimbabwean')) ) BEGIN  INSERT INTO NationalityLU VALUES(UPPER('Zimbabwean')); END
GO