PRINT N'Altering [dbo].[Personnel]...';

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel' AND COLUMN_NAME = 'AddrBaranggay')
    ALTER TABLE [dbo].[Personnel] ADD [AddrBaranggay] NVARCHAR(100) DEFAULT ('') NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel' AND COLUMN_NAME = 'Baranggay')
    ALTER TABLE [dbo].[Personnel] ADD [Baranggay] NVARCHAR(100) DEFAULT ('') NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel' AND COLUMN_NAME = 'AddrTelNo')
    ALTER TABLE [dbo].[Personnel] ADD [AddrTelNo] NVARCHAR(100) DEFAULT ('') NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel' AND COLUMN_NAME = 'Address5')
    ALTER TABLE [dbo].[Personnel] ADD [Address5] NVARCHAR(100) DEFAULT ('') NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel' AND COLUMN_NAME = 'Address6')
    ALTER TABLE [dbo].[Personnel] ADD [Address6] NVARCHAR(100) DEFAULT ('') NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel' AND COLUMN_NAME = 'PermanentComplexUnitNo')
    ALTER TABLE [dbo].[Personnel] ADD [PermanentComplexUnitNo] NVARCHAR(100) DEFAULT ('') NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel' AND COLUMN_NAME = 'PermanentComplexName')
    ALTER TABLE [dbo].[Personnel] ADD [PermanentComplexName] NVARCHAR(100) DEFAULT ('') NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel' AND COLUMN_NAME = 'PermanentBaranggay')
    ALTER TABLE [dbo].[Personnel] ADD [PermanentBaranggay] NVARCHAR(100) DEFAULT ('') NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel' AND COLUMN_NAME = 'PermanentStreetName')
    ALTER TABLE [dbo].[Personnel] ADD [PermanentStreetName] NVARCHAR(100) DEFAULT ('') NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel' AND COLUMN_NAME = 'PermanentSubdivision')
    ALTER TABLE [dbo].[Personnel] ADD [PermanentSubdivision] NVARCHAR(100) DEFAULT ('') NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel' AND COLUMN_NAME = 'PermanentCity')
    ALTER TABLE [dbo].[Personnel] ADD [PermanentCity] NVARCHAR(100) DEFAULT ('') NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel' AND COLUMN_NAME = 'PermanentPostalCode')
    ALTER TABLE [dbo].[Personnel] ADD [PermanentPostalCode] NVARCHAR(100) DEFAULT ('') NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel' AND COLUMN_NAME = 'PermanentTelNo')
    ALTER TABLE [dbo].[Personnel] ADD [PermanentTelNo] NVARCHAR(100) DEFAULT ('') NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel' AND COLUMN_NAME = 'PermanentHouseNumber')
    ALTER TABLE [dbo].[Personnel] ADD [PermanentHouseNumber] NVARCHAR(100) DEFAULT ('') NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel' AND COLUMN_NAME = 'CityOfBirth')
    ALTER TABLE [dbo].[Personnel] ADD [CityOfBirth] NVARCHAR(50) DEFAULT ('') NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel' AND COLUMN_NAME = 'ExemptionClaim')
    ALTER TABLE [dbo].[Personnel] ADD [ExemptionClaim] SMALLINT DEFAULT ('') NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel' AND COLUMN_NAME = 'Fixed')
    ALTER TABLE [dbo].[Personnel] ADD [Fixed] NVARCHAR(100) DEFAULT ('') NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel' AND COLUMN_NAME = 'EmpTaxID')
    ALTER TABLE [dbo].[Personnel] ADD [EmpTaxID] NVARCHAR(20) DEFAULT ('') NULL
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel' AND COLUMN_NAME = 'RecInterestHob')--2020/02/25
    ALTER TABLE [dbo].[Personnel] ADD [RecInterestHob] NVARCHAR(MAX) DEFAULT ('') NULL 
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel' AND COLUMN_NAME = 'NOK_age')--2020/03/13
    ALTER TABLE [dbo].[Personnel] ADD [NOK_age] INT DEFAULT NULL 
GO