IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PersonnelAttribute' AND COLUMN_NAME = 'Category')
	ALTER TABLE [PersonnelAttribute] ALTER COLUMN [Category] VARCHAR(10) NULL