PRINT N'Altering [dbo].[Personnel1]...';

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel1' AND COLUMN_NAME = 'Fixed')
    ALTER TABLE [dbo].[Personnel1] ADD [Fixed] NVARCHAR(100) DEFAULT ('') NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel1' AND COLUMN_NAME = 'SpouseAddress')
    ALTER TABLE [dbo].[Personnel1] ADD [SpouseAddress] NVARCHAR(100) DEFAULT ('') NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Personnel1' AND COLUMN_NAME = 'SpouseSex')
    ALTER TABLE [dbo].[Personnel1] ADD [SpouseSex] NVARCHAR(100) DEFAULT ('') NULL

GO