/****** Object:  StoredProcedure [dbo].[prInsertToPH]    Script Date: 3/22/2019 1:42:31 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[dbo].[prInsertToPH]') AND OBJECTPROPERTY(ID, N'ISPROCEDURE') = 1)
BEGIN
	PRINT 'Dropping Procedure prInsertToPH'
	DROP PROCEDURE [dbo].[prInsertToPH]	
END

PRINT N'Creating [dbo].[prInsertToPH]...';
GO

CREATE procedure [dbo].[prInsertToPH]
@EMPLOYEE_NUMBER VARCHAR(50),
@PROMOTION_DATE DATETIME,
@EMPLOYEE_CATEGORY VARCHAR(100),
@PAY_LEVEL VARCHAR(5),
@JOB_GRADE VARCHAR(5),
@EMPLOYEE_CLASS VARCHAR(100),
@POSITION VARCHAR(200)
AS
BEGIN
	INSERT INTO [prPromotionHistory] 
	VALUES 
	(
		@EMPLOYEE_NUMBER,@PROMOTION_DATE,@EMPLOYEE_CATEGORY,
		@PAY_LEVEL,@JOB_GRADE,@EMPLOYEE_CLASS,@POSITION
	)
END
