/****** Object:  View [dbo].[alphabets]    Script Date: 4/3/2019 6:00:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS(SELECT 1 FROM sys.views WHERE [Name] = 'alphabets' AND [Type]='V')
	DROP VIEW alphabets;
GO

PRINT N'Creating [dbo].[alphabets]...';
GO

CREATE VIEW [dbo].[alphabets]
AS
	SELECT 'a' AS A
		UNION ALL SELECT 'b' UNION ALL SELECT 'c' UNION ALL SELECT 'd' UNION ALL SELECT 'e' UNION ALL SELECT 'f'
		UNION ALL SELECT 'g' UNION ALL SELECT 'h' UNION ALL SELECT 'i' UNION ALL SELECT 'j' UNION ALL SELECT 'k'
		UNION ALL SELECT 'l' UNION ALL SELECT 'm' UNION ALL SELECT 'n' UNION ALL SELECT 'o' UNION ALL SELECT 'p'
		UNION ALL SELECT 'q' UNION ALL SELECT 'r' UNION ALL SELECT 's' UNION ALL SELECT 't' UNION ALL SELECT 'u'
		UNION ALL SELECT 'v' UNION ALL SELECT 'w' UNION ALL SELECT 'x' UNION ALL SELECT 'y' UNION ALL SELECT 'z'

GO