/****** Object:  View [dbo].[prViewNewData]    Script Date: 4/3/2019 6:00:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS(SELECT 1 FROM sys.views WHERE [Name] = 'prViewNewData' AND [Type]='V')
	DROP VIEW prViewNewData;
GO

PRINT N'Creating [dbo].[prViewNewData]...';
GO


CREATE VIEW [dbo].[prViewNewData]
AS
	SELECT
		A.PERIOD_FROM	AS 'PERIOD FROM'
	   ,A.PERIOD_TO		AS 'PERIOD TO'
	   ,A.RATE_DATE		AS 'RATE DATE'
	   ,A.RATER			AS 'RATER'
	   ,A.RATE_CODE		AS 'RATE'
	   ,A.MAN_NO		AS 'EMPLOYEE NUMBER'
	   ,A.JOBTITLE_CODE	AS 'JOB TITLE'
	   ,A.PAYLVL_CODE	AS 'PAY LEVEL CODE'
	   ,A.RATE_TYPE		AS 'RATE TYPE'
	   ,A.PAYGRP_CODE	AS 'PAY GROUP CODE'
	FROM prTempPerformance a FULL JOIN prPerformance b
		ON b.MAN_NO = a.MAN_NO
			AND b.PERIOD_FROM = a.PERIOD_FROM
			AND b.PERIOD_TO = a.PERIOD_TO
			AND b.RATE_DATE = a.RATE_DATE
			AND b.RATER = a.RATER
			AND b.RATE_CODE = a.RATE_CODE
			AND b.JOBTITLE_CODE = a.JOBTITLE_CODE
			AND b.PAYLVL_CODE = a.PAYLVL_CODE
			AND b.RATE_TYPE = a.RATE_TYPE
			AND b.PAYGRP_CODE = a.PAYGRP_CODE
	WHERE b.MAN_NO IS NULL

GO