-- ======================================= --
--  CREATED BY: RANDOLPH BENJO T. NAANEP   --
--      GURANGO SOFTWARE CORPORATION       --
-- ======================================= --

IF EXISTS(SELECT 1 FROM sys.views WHERE [Name] = 'vwPersonnelInformation' AND [Type] = 'V')
	DROP VIEW vwPersonnelInformation;
GO

PRINT N'Creating [dbo].[vwPersonnelInformation]...';
GO

CREATE VIEW [dbo].[vwPersonnelInformation]
AS
	SELECT
		A.[CompanyNum]
	   ,A.[EmployeeNum]
	   ,A.[PreferredName]
	   ,A.[Title]
	   ,A.[Initials]
	   ,A.[Surname]
	   ,A.[FirstName]
	   ,A.[MiddleName]
	   ,A.[MaidenName]
	   ,A.[IDNum]
	   ,A.[Sex]
	   ,A.[Nationality]
	   ,A.[BirthDate]
	   ,A.[CityOfBirth]
	   ,A.[BloodType]
	   ,[dbo].[fnCalculateAge](BirthDate) AS [Age]
	   ,A.[ZodiacSign]
	   ,A.[ZodiacSignActual]
	   ,A.[Language]
	   ,A.[Religion]
	   ,A.[EthnicGroup]
	   ,A.[MaritialStatus] AS [MaritalStatus]
	   ,B.[MarriageDate]
	   ,A.[ExemptionClaim]
	   ,A.[Disability]
	   ,A.[DisabilityNotes]
	   ,A.[ShuttleRoute]
	   ,A.[Address1]
	   ,A.[Address2]
	   ,A.[Address3]
	   ,A.[Address4]
	   ,A.[Address5]
	   ,A.[Address6]
	   ,A.[POBox]
	   ,A.[POArea]
	   ,A.[POCode]
	   ,A.[OfficeNo]
	   ,A.[CellTel]
	   ,A.[ExtensionNo]
	   ,A.[HomeTel]
	   ,A.[EMailAddress]
	   ,A.[AddrUnit]
	   ,A.[AddrComplex]
	   ,A.[AddrStreetNo]
	   ,A.[AddrStreetName]
	   ,A.[AddrSuburb]
	   ,A.[AddrCity]
	   ,A.[AddrZip]
	   ,A.[Latitude]
	   ,A.[Longitude]
	   ,A.[EMailAddress1]
	   ,A.[FaxNo]
-------SPOUSE INFORMATION
	   ,B.[SpouseSurname]
	   ,A.[SpouseName]
	   ,A.[SpouseMiddleName]
	   ,B.[SpouseDOB]
	   ,[dbo].[fnCalculateAge](B.SpouseDOB) AS [SpouseAge]
	   ,B.[SpouseSex]
	   ,A.[SpouseTel]
	   ,B.[SpouseAddress]
	   ,A.[SpouseNationality]
	   ,A.[SpouseOccu]
	   ,A.[SpouseEmployer]
	   ,A.[SpouseEmployerAdd]
	   ,A.[NOK_Surname]
	   ,A.[NOK_FirstName]
	   ,A.[NOK_MiddleName]
	   ,A.[NOK_DateOfBirth]
	   ,[dbo].[fnCalculateAge](A.NOK_DateOfBirth) AS [NOK_Age]
	   ,A.[NOK_Gender]
	   ,A.[NOK_Relationship]
	   ,A.[NOK_ERAddress]
	   ,A.[NOK_ContactNo]
	   ,A.[NOK_Occupation]
	   ,A.[NOK_Employer]
	   ,A.[BIRMembershipNo]
	   ,A.[SSSMembershipNo]
	   ,A.[PAGIBIGMembershipNo]
	   ,A.[PHILMemNo]
       ,B.[TownOfBirth]
	   ,B.[CountryOfBirth]
	   ,(CASE A.RecInterestHob WHEN NULL THEN C.RecInterestHob ELSE A.RecInterestHob END) as [RecInterestHob]
	   ,A.[AddrRegion]
	   ,A.[TaxCode]
	   ,A.[AddrBaranggay]
	   ,A.[Baranggay]
	   ,A.[AddrState]
	   ,A.[AddrTelNo]
	   ,A.[PermanentComplexUnitNo]
	   ,A.[PermanentComplexName]
	   ,A.[PermanentHouseNumber]
	   ,A.[PermanentStreetName]
	   ,A.[PermanentSubdivision]
	   ,A.[Region]
	   ,A.[State_or_Province]
	   ,A.[PermanentCity]
	   ,A.[PermanentBaranggay]
	   ,A.[PermanentPostalCode]
	   ,A.[PermanentTelNo]
	FROM [Personnel]						 AS A
		LEFT OUTER JOIN [Personnel1]		 AS B ON A.CompanyNum = B.CompanyNum AND A.EmployeeNum = B.EmployeeNum
		LEFT OUTER JOIN [RecPositionApplied] AS C ON A.CompanyNum = C.CompanyNum AND A.EmployeeNum = C.EmployeeNum
        
GO